package com.bydan.framework.erp.util;

public enum ControlTipo {
	WINDOW,FORM,PANEL,TABLE,TREE,MENU,BUTTON,LABEL,TEXTBOX,TEXTAREA,COMBOBOX,LISTBOX,DATE,CHECKBOX,RADIO,FILE,IMAGE,KEY,MESSAGE,SCROLL,TAB,TOOLTIP,NINGUNO
}