package com.bydan.framework.erp.util;

public enum EventoSubTipo {
	CLICKED,CHANGED,PRESSED,OPENED,ACTIVATED,DEACTIVATED,RELEASED,ENTERED,EXITED,CLOSED,CLOSING,NEW,UPDATE,DELETE,SELECTED,NINGUNO
}
