package com.bydan.framework.erp.util;

public enum ParameterType {
	BIGDECIMAL,BINARYSTREAM,BLOB,BOOLEAN,BYTE,BYTES,CHARACTERSTREAM,CLOB,DATE,DOUBLE,FLOAT,SHORT,INT,LONG,NCHARACTERSTREAM,NCLOB,NSTRING,NULL,
	OBJECT,STRING,TIME,TIMESTAMP,NONE
}
